name: Build Frontend Image

on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
      module_path:
        required: true
        type: string
      workdir:
        required: true
        type: string
      needs_push:
        required: false
        type: boolean
        default: false
      repo:
        required: true
        type: string
      tag:
        required: true
        type: string
jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: amd64
          - arch: arm64
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on || 'ubuntu-24.04' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ inputs.repo }}
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/${{ matrix.arch }}
          build-args: |
            name=${{ inputs.module_name }}
            path=${{ inputs.module_path }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,"name=${{ inputs.repo }}",name-canonical=true,push-by-digest=${{ inputs.needs_push }},push=${{ inputs.needs_push }}
      - name: Export digest
        env:
          DIGEST: ${{ steps.build.outputs.digest }}
        run: |
          mkdir -p "${{ runner.temp }}/digests"
          touch "${{ runner.temp }}/digests/${DIGEST#sha256:}"
      - name: Upload digest
        if: ${{ inputs.needs_push }}
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ inputs.module_name }}-${{ matrix.arch }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1
  merge:
    needs: [build]
    name: Merge and push docker images
    if: ${{ inputs.needs_push }}
    uses: ./.github/workflows/merge-and-push.yml
    with:
      image_name: ${{ inputs.repo }}
      tag_name: ${{ inputs.tag }}
      module_name: ${{ inputs.module_name }}