
name: Default frontend workflow
on:
  workflow_call:
    inputs:
      comp:
        type: string
        default: "frontend" 
      module_name:
        required: true
        type: string
      module_path:
        required: true
        type: string
      workdir:
        type: string
        default: "frontend"
      push:
        type: boolean
        default: false
jobs:
  prepare-image-info:
    uses: ./.github/workflows/prepare-image-info.yml
    with:
      module_name: ${{ inputs.module_name }}
      comp: ${{ inputs.comp }}
      needs_push: ${{ inputs.push }}
  build-image:
    needs: [prepare-image-info]
    uses: ./.github/workflows/build-frontend-image.yml
    with:
      module_name: ${{ inputs.module_name }}
      module_path: ${{ inputs.module_path }}
      workdir: ${{ inputs.workdir }}
      needs_push: ${{ inputs.push }}
      repo: ${{ needs.prepare-image-info.outputs.cur_docker_repo }}
      tag: ${{ needs.prepare-image-info.outputs.tag_name }}
  build-frontend-cluster-image:
    if: ${{ inputs.push == 'true' }}
    needs: [build-image, prepare-image-info]
    uses: ./.github/workflows/build-cluster-image.yml
    with:
      module_name: ${{ inputs.module_name }}
      module_path: ${{ inputs.module_path }}
      workdir: ${{ inputs.workdir }}
      cur_cluster_repo: ${{ needs.prepare-image-info.outputs.cur_cluster_repo }}
      orig_docker_repo: ${{ needs.prepare-image-info.outputs.orig_docker_repo }}
      cur_docker_repo: ${{ needs.prepare-image-info.outputs.cur_docker_repo }}
      tag_name: ${{ needs.prepare-image-info.outputs.tag_name }} 